### ISSUE TITLE
Sort reads when visualize data

### ISSUE THREAD

**Issue by Yiming-Shen** [nspies/genomeview#13]
Hi Noah, I found Genomiew is quite a convenient tool to automatically generate genome visualization pictures on servers without X11 display function. 
Is it possible to sort reads in output pictures? Maybe by mapping qualities so that mutant reads can be shown on the top or by first mapped base to show reads in order.

**Comment by nspies** [comment]
Hrm, while I've tried the "sort by x" feature in IGV, I can't say I ever figured out how it worked or was useful. Maybe when you have really deep coverage somewhere? For something like splitting by allele, I'd start from the [`GroupedBAMTrack`](https://genomeview.readthedocs.io/en/latest/bams.html#genomeview.GroupedBAMTrack) and provide a keyfn that separates ref- and alt- reads for a given position of interest.

Genomeview doesn't do sorting out of the box, but you could consider inheriting from `SingleEndBAMTrack` or `PairedEndBAMTrack` and adjusting the sort order which is defined here: https://github.com/nspies/genomeview/blob/master/genomeview/bamtrack.py#L321

If you're feeling more ambitious, I'm happy to accept pull requests -- this would involve refactoring a bit so that an arbitrary sort function could be selected for a given bamtrack instance; and an example jupyter notebook and test dataset demonstrating the effects of unsorted + sorted outputs.
