### ISSUE TITLE
How to output png files?

### ISSUE THREAD

**Issue by ghost** [nspies/genomeview#21]
Dear @nspies sorry for bothering you but I am stuck at the step of outputting png files instead of SVG files.

In your doc, you said that to output SVG files, we need to install two more packages which are Inkscape and libRsvg if we want to convert the files to png format.

The thing is, I tried to implement the steps into a pipeline that works on a server HPC, while Inkscape seems to be an independent software using the GUI interface. Therefore I cannot implement the png conversion into a pipeline on the cloud. 

While another thing is if the conversion is not available, the SVG files sometimes are so big and I cannot store them. For one VCF file, I may have hundreds of SVG files corresponding to hundreds of variant records. I once saw an SVG file sizing around 1.7 Gb and when I open it with chrome it shows no errors, meaning it supposes to be that big.... In the end, transferring BAM files are actually easier than transferring SVG files...

If available, would you pls recommend a solution that I can implement into a pipeline to output png files instead of svg files?

**Comment by nspies** [comment]
I can't help with the file size of the svgs, but inkscape runs fine from the command line in an hpc setup.

**Comment by yangyxt** [comment]
> I can't help with the file size of the svgs, but Inkscape runs fine from the command line in an HPC setup.

Dear @nspies, thanks for your reply. I took a look at those extremely large SVG files and found that all of them have a large amount of <path> XML nodes having an attribute "fill" with the value "transparent". I suppose they are not useful after rendering the SVG file. 

I removed them with AWK and found the file size shrinks from several gigabytes to 1-2Mb. And the rendered pic stays the same. And without removing them, the SVG file cannot be converted by libRsvg due to an XML node amount limitation on libRsvg. Plus, even without the limitation, handling this large SVG file may cause memory leakage.

Anyway, If you found this a glitch and you have time, you can take a look into this issue. Thanks for your reply!
